#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Ján Bogár

# Short bio or description (displayed in the header)
description: Osobná stránka

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/profilovka.jpg

#
# Flags below are optional
#

#disabled
# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: jan.boogie.bogar@gmail.com
  facebook: jan.bogar
  flickr:
  github: 
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: janbogar-github-io

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-81933109-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - materialy


#translations of common words
t:
 en:
  name: "Ján Bogár"
  description: "Personal Website"
  about: "About me"
  influences: "What influenced me"
  i_like: "What I like"
  i_know: "What I can do"
  contacts: "Contacts"
  i_did: "What I already did"
  read_more: "Read more"
  tags: "Tags"
 sk:
  name: "Ján Bogár"
  description: "Osobná stránka"
  about: "O mňe"
  influences: "Čo ma ovplyvnilo"
  i_like: "Čo mám rád"
  i_know: "Čo viem"
  contacts: "Kontakty"
  i_did: "Čo som už urobil"
  read_more: "Čítaj ďalej"
  tags: "Tagy"

#tags
taglist:
 en:
 sk:
  "ľahká fyzika": lahka_fyzika
